version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for API Lambda"
      - pip install --upgrade pip
      - pip install -r Lambda/API/requirements.txt -t Lambda/API/
      - echo "Installing dependencies for Collector Lambda"
      - pip install -r Lambda/Collector/requirements.txt -t Lambda/Collector/
  build:
    commands:
      - echo "Zipping Lambda functions"
      - cd Lambda/API && zip -r ../../api.zip * && cd ../../
      - cd Lambda/Collector && zip -r ../../collector.zip * && cd ../../
      - echo "Uploading zips to S3 bucket for Lambda deployment"
      - aws s3 cp api.zip s3://crypto-tracker-lambda-code/api.zip
      - aws s3 cp collector.zip s3://crypto-tracker-lambda-code/collector.zip
      - echo "Build and upload completed"
artifacts:
  files:
    - api.zip
    - collector.zip
    - infrastructure/template.yaml